name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.0"

      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test || true

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Build APK
        run: flutter build apk
